name: Validate

on:  # Definisce quando eseguire questi controlli
  push:  # Quando viene fatto un push
  pull_request:  # Quando viene creata una pull request
  schedule:
    - cron: "0 0 * * *"  # Una volta al giorno a mezzanotte

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"  # Scarica il codice del repository
        with:
          node-version: 20
      - uses: "home-assistant/actions/hassfest@master"  # Esegue hassfest
      - uses: "hacs/action@main"  # Esegue la validazione HACS
        with:
          category: "integration"